image:
  tag: 2.0.0

service:
  type: NodePort
  port: 8080

replicaCount: 6

ingress:
  enabled: true
  domainName: cda.cda-dev.broadinstitute.org
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cda-dev-ip
  hosts:
    - host: cda.cda-dev.broadinstitute.org
      paths:
        - /*

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: bq-cda-sa@broad-cda-dev.iam.gserviceaccount.com
