image:
  tag: 0.0.4-SNAPSHOT

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  domainName: cda.cda-dev.broadinstitute.org
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cda-dev-ip
  hosts:
    - host: cda.cda-dev.broadinstitute.org
      paths:
        - /*
  tls:
    - hosts:
      - cda.cda-dev.broadinstitute.org

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: bq-cda-sa@broad-cda-dev.iam.gserviceaccount.com
